### ISSUE TITLE
Support for PEP-592 (yanked releases)

### ISSUE THREAD

**Issue by sdispater** [python-poetry/roadmap#2]
PyPI and pip recently added support for "yanked" releases ([PEP-592](https://www.python.org/dev/peps/pep-0592/)).

We should add support for it in Poetry as well.

This should be handled in two places:

- In the `PyPiRepository` class: the PyPI JSON API provides a `yanked` property at the release level that we can use to flag a file as yanked.
- In the `LegacyRepository` class: this one should follow the PEP to retrieve the "yanked" information.

**Comment by neersighted** [comment]
Completed in 1.2
